src/main/java/de/interfaceag/bmw/pzbk/berechtigung/dto/BerechtigungDto.java
package de.interfaceag.bmw.pzbk.berechtigung.dto;

import de.interfaceag.bmw.pzbk.enums.BerechtigungZiel;
import de.interfaceag.bmw.pzbk.enums.Rechttype;
import de.interfaceag.bmw.pzbk.enums.Rolle;

import java.io.Serializable;

/**
 *
 * @author sl (stefan.luchs@interface-ag.de)
 */
public interface BerechtigungDto extends Serializable {

    Long getId();

    String getName();

    Rechttype getRechttype();

    Rolle getRolle();

    BerechtigungZiel getType();

    @Override
    String toString();

}

src/main/java/de/interfaceag/bmw/pzbk/berechtigung/dto/BerechtigungEditDto.java
package de.interfaceag.bmw.pzbk.berechtigung.dto;

/**
 *
 * @author sl (stefan.luchs@interface-ag.de)
 */
public interface BerechtigungEditDto extends BerechtigungDto {

    boolean isDelete();

    void setDelete(boolean delete);

    boolean getEditPermission();

}

src/main/java/de/interfaceag/bmw/pzbk/berechtigung/BerechtigungController.java
package de.interfaceag.bmw.pzbk.berechtigung;

import de.interfaceag.bmw.pzbk.berechtigung.dto.MitarbeiterDTO;
import de.interfaceag.bmw.pzbk.entities.Mitarbeiter;
import de.interfaceag.bmw.pzbk.services.UserSearchService;
import de.interfaceag.bmw.pzbk.session.Session;
import de.interfaceag.bmw.pzbk.shared.utils.UrlParameterUtils;
import org.primefaces.context.RequestContext;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.util.List;

@ViewScoped
@Named
public class BerechtigungController implements Serializable {

    //---------new------------------------
    @Inject
    private BerechtigungViewFacade berechtigungViewFacade;

    private BerechtigungViewData berechtigungViewData;

    //-------------------------------
    @Inject
    private Session session;
    @Inject
    private UserSearchService userSearchService;
    @Inject
    private MitarbeiterZuordnenDialogController mitarbeiterZuordnenDialogController;

    private BerechtigungViewPermission viewPermission;

    @PostConstruct
    public void init() {

        session.setLocationForView();

        initViewPermission();

        initViewData();

    }
    //----------------------------------new Methods----------------------------------------

    private void initViewData() {
        berechtigungViewData = berechtigungViewFacade.getViewData(UrlParameterUtils.getUrlParameter());
    }

    private void initViewPermission() {
        viewPermission = BerechtigungViewPermission.builder()
                .forUserRoles(session.getUserPermissions().getRoles())
                .build();
    }

    public BerechtigungViewData getViewData() {
        return berechtigungViewData;
    }

    public BerechtigungViewFilter getFilter() {
        return berechtigungViewData.getFilter();
    }

    public String reset() {
        return getFilter().getResetUrl();
    }

    public String filter() {
        return getFilter().getUrl();
    }

    public List<MitarbeiterDTO> getTableData() {
        return getViewData().getTableData();
    }
    //---------------------old used Methods

    public String processInput() {
        // process data
        getMitarbeiterZuordnenDialogController().addUsersToRole();
        // process wizard dialog
        processWizard();
        // reset dialog
        getMitarbeiterZuordnenDialogController().resetInputFields();
        return filter();
    }

    private void processWizard() {
        getMitarbeiterZuordnenDialogController().processWizard();
        RequestContext context = RequestContext.getCurrentInstance();
        context.update("viewAdmContent:adminAccordionPanel:benutzerverwaltungForm");
    }

    public void showAddZuordnungDialog(Long mitarbeiterId) {
        if (mitarbeiterId != null) {
            Mitarbeiter mitarbeiter = userSearchService.getUniqueMitarbeiterById(mitarbeiterId);
            RequestContext context = RequestContext.getCurrentInstance();
            context.execute("PF('mitarbeiterBearbeitenDialog').hide()");
            mitarbeiterZuordnenDialogController.showAddZuordnungDialog(mitarbeiter);
            context.update("dialog:mitarbeiterBearbeitenForm");
        }
    }

    public MitarbeiterZuordnenDialogController getMitarbeiterZuordnenDialogController() {
        return mitarbeiterZuordnenDialogController;
    }

    public BerechtigungViewPermission getViewPermission() {
        return viewPermission;
    }

}

src/main/java/de/interfaceag/bmw/pzbk/berechtigung/MitarbeiterBearbeitenDialogController.java
package de.interfaceag.bmw.pzbk.berechtigung;

import de.interfaceag.bmw.pzbk.berechtigung.dto.BerechtigungDto;
import de.interfaceag.bmw.pzbk.berechtigung.dto.BerechtigungEditDto;
import de.interfaceag.bmw.pzbk.entities.Mitarbeiter;
import de.interfaceag.bmw.pzbk.entities.Tteam;
import de.interfaceag.bmw.pzbk.enums.Rolle;
import de.interfaceag.bmw.pzbk.permissions.UserPermissions;
import de.interfaceag.bmw.pzbk.permissions.components.MitarbeiterBearbeiterDialogViewPermission;
import de.interfaceag.bmw.pzbk.services.BerechtigungService;
import de.interfaceag.bmw.pzbk.services.TteamService;
import de.interfaceag.bmw.pzbk.services.UserSearchService;
import de.interfaceag.bmw.pzbk.session.Session;
import org.primefaces.context.RequestContext;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * @author sl (stefan.luchs@interface-ag.de)
 */
@Named
@ViewScoped
public class MitarbeiterBearbeitenDialogController implements Serializable {

    @Inject
    private Session session;

    @Inject
    private UserSearchService userSearchService;
    @Inject
    private BerechtigungService berechtigungService;
    @Inject
    private UserPermissionsService userPermissionsService;
    @Inject
    private TteamService tteamService;

    private Mitarbeiter mitarbeiterToEdit;

    private final List<Rolle> rollenZuEntziehen = new ArrayList<>();

    private final List<BerechtigungEditDto> berechtigungenZuEntziehen = new ArrayList<>();

    private final List<Long> tteamZuEntziehenForTteamMitgliedSchreibend = new ArrayList<>();

    private final List<Long> tteamZuEntziehenForTteamMitgliedLesend = new ArrayList<>();

    private final List<Long> tteamZuEntziehenForTteamVertreter = new ArrayList();

    private UserPermissions<BerechtigungEditDto> userPermissions;

    private MitarbeiterBearbeiterDialogViewPermission viewPermission;

    private String urlParameter;

    // ---------- frontend methods ---------------------------------------------
    public void showMitarbeiterBearbeitenDialog(Long mitarbeiterId, String urlParameter) {
        this.urlParameter = urlParameter;
        updateDialogData(mitarbeiterId);
        RequestContext context = RequestContext.getCurrentInstance();
        context.update("dialog:mitarbeiterBearbeitenForm");
        context.execute("PF('mitarbeiterBearbeitenDialog').show()");

    }

    public void clearRolleZuEntziehenList() {
        rollenZuEntziehen.clear();
        berechtigungenZuEntziehen.clear();
    }

    private void updateDialogData(Long mitarbeiterId) {
        this.mitarbeiterToEdit = userSearchService.getUniqueMitarbeiterById(mitarbeiterId);
        Set<Rolle> currentUserRoles = session.getUserPermissions().getRoles();
        Set<Long> sensorCocIds = session.getUserPermissions()
                .getSensorCocAsSensorCocLeiterSchreibend()
                .stream().map(BerechtigungDto::getId).collect(Collectors.toSet());
        this.userPermissions = userPermissionsService.getUserPermissionsWithEditPermissions(mitarbeiterToEdit, currentUserRoles, sensorCocIds);
        Set<Rolle> editUserRoles = this.userPermissions.getRoles();
        this.viewPermission = new MitarbeiterBearbeiterDialogViewPermission(editUserRoles, currentUserRoles);
    }

    // ----------- methods -----------------------------------------------------
    public String processChanges() {
        berechtigungService.removeBerechtigungen(berechtigungenZuEntziehen, mitarbeiterToEdit);
        berechtigungService.removeTteamMitgliedBerechtigungen(mitarbeiterToEdit, tteamZuEntziehenForTteamMitgliedLesend, tteamZuEntziehenForTteamMitgliedSchreibend);
        berechtigungService.removeTteamVertreterdBerechtigungen(mitarbeiterToEdit, tteamZuEntziehenForTteamVertreter);

        return urlParameter;
    }

    public boolean isTteamSelectedByMitgliedForDeleteWritable(String tteam) {
        if (tteam != null && !"".equals(tteam)) {
            return tteamZuEntziehenForTteamMitgliedSchreibend.contains(tteamService.getTteamByName(tteam).getId());
        } else {
            return Boolean.FALSE;
        }
    }

    public boolean isTteamSelectedByMitgliedForDeleteReadable(String tteam) {
        if (tteam != null && !"".equals(tteam)) {
            return tteamZuEntziehenForTteamMitgliedLesend.contains(tteamService.getTteamByName(tteam).getId());
        } else {
            return Boolean.FALSE;
        }
    }

    public boolean isTteamSelectedByVertreterForDelete(String tteam) {
        if (tteam != null && !"".equals(tteam)) {
            return tteamZuEntziehenForTteamVertreter.contains(tteamService.getTteamByName(tteam).getId());
        } else {
            return Boolean.FALSE;
        }
    }

    public boolean checkForTteamMitgliedWritingDeleteButton(String tteam) {
        if (tteam != null && !"".equals(tteam)) {
            return !isTteamSelectedByMitgliedForDeleteWritable(tteam) && hasTteamLeiterRightsToEdit(tteam);
        } else {
            return Boolean.FALSE;
        }
    }

    public boolean checkForTteamMitgliedReadingDeleteButton(String tteam) {
        if (tteam != null && !"".equals(tteam)) {
            return !isTteamSelectedByMitgliedForDeleteReadable(tteam) && hasTteamLeiterRightsToEdit(tteam);
        } else {
            return Boolean.FALSE;
        }
    }

    public boolean checkForTteamVertreterDeleteButton(String tteam) {
        if (tteam != null && !"".equals(tteam)) {
            return !isTteamSelectedByVertreterForDelete(tteam) && hasTteamLeiterRightsToEdit(tteam);
        } else {
            return Boolean.FALSE;
        }
    }

    public String resetChanges() {
        return urlParameter;
    }

    public void stripRoleAdmin() {
        addRolleZuEntziehen(Rolle.ADMIN);
        addBerechtigungToRemoveList(userPermissions.getAdminBerechtigung());
    }

    public void stripRoleSensor() {
        addRolleZuEntziehen(Rolle.SENSOR);
        addBerechtigungenToRemoveList(getSensorCocAsSensorLesend());
        addBerechtigungenToRemoveList(getSensorCocAsSensorSchreibend());
    }

    public void stripRoleSensorEingeschraenkt() {
        addRolleZuEntziehen(Rolle.SENSOR_EINGESCHRAENKT);
        addBerechtigungenToRemoveList(getSensorCocAsSensorEingSchreibend());
    }

    public void stripRoleSensorCoCLeiter() {
        addRolleZuEntziehen(Rolle.SENSORCOCLEITER);
        addBerechtigungenToRemoveList(getSensorCocAsSensorCocLeiterLesend());
        addBerechtigungenToRemoveList(getSensorCocAsSensorCocLeiterSchreibend());
        addBerechtigungenToRemoveList(getSensorCocAsUmsetzungsbestaetigerSchreibend(), Rolle.SENSORCOCLEITER);
    }

    public void stripRoleVertreterSCL() {
        addRolleZuEntziehen(Rolle.SCL_VERTRETER);
        addBerechtigungenToRemoveList(getSensorCocAsVertreterSCLLesend());
        addBerechtigungenToRemoveList(getSensorCocAsVertreterSCLSchreibend());
        addBerechtigungenToRemoveList(getSensorCocAsUmsetzungsbestaetigerSchreibend(), Rolle.SCL_VERTRETER);
    }

    public void stripRoleTteamleiter() {
        addRolleZuEntziehen(Rolle.T_TEAMLEITER);
        addBerechtigungenToRemoveList(getTteamAsTteamleiterSchreibend());
    }

    public void stripRoleECoC() {
        addRolleZuEntziehen(Rolle.E_COC);
        addBerechtigungenToRemoveList(getModulSeTeamAsEcocSchreibend());
    }

    public void stripRoleAnforderer() {
        addRolleZuEntziehen(Rolle.ANFORDERER);
        addBerechtigungenToRemoveList(getDerivatAsAnfordererSchreibend());
        addBerechtigungenToRemoveList(getZakEinordnungAsAnfordererSchreibend());
    }

    public void stripRoleUmsetzungsbestaetiger() {
        addRolleZuEntziehen(Rolle.UMSETZUNGSBESTAETIGER);
        addBerechtigungenToRemoveList(getSensorCocAsUmsetzungsbestaetigerSchreibend());
    }

    public void stripRoleLeser() {
        addBerechtigungenToRemoveList(getSensorCocAsLeser());
        addRolleZuEntziehen(Rolle.LESER);
    }

    public void stripRoleTteamMitglied() {
        addRolleZuEntziehen(Rolle.TTEAMMITGLIED);
        tteamZuEntziehenForTteamMitgliedLesend.addAll(userPermissions.getTteamIdsForTteamMitgliedLesend());
        tteamZuEntziehenForTteamMitgliedSchreibend.addAll(userPermissions.getTteamIdsForTteamMitgliedSchreibend());
    }

    public void stripeRoleTteamVertreter() {
        addRolleZuEntziehen(Rolle.TTEAM_VERTRETER);
        tteamZuEntziehenForTteamVertreter.addAll(userPermissions.getTteamIdsForTteamVertreter());
    }

    private void addRolleZuEntziehen(Rolle rolle) {
        rollenZuEntziehen.add(rolle);
    }

    private void addBerechtigungenToRemoveList(List<BerechtigungEditDto> berechtigungen) {
        berechtigungen.forEach(b -> b.setDelete(true));
        this.berechtigungenZuEntziehen.addAll(berechtigungen);
    }

    private void addBerechtigungenToRemoveList(List<BerechtigungEditDto> berechtigungen, Rolle rolle) {
        List<Long> sensorCocIds = new ArrayList<>();
        switch (rolle) {
            case SENSORCOCLEITER:
                sensorCocIdsForSensorCocLeiter(sensorCocIds);
                break;

            case SCL_VERTRETER:
                sensorCocIdsForSensorCocVertreter(sensorCocIds);
                break;
            default:
                break;
        }

        berechtigungen.stream().filter(b -> sensorCocIds.contains(b.getId()))
                .forEachOrdered(b -> {
                    b.setDelete(true);
                    this.berechtigungenZuEntziehen.add(b);
                });
    }

    private void sensorCocIdsForSensorCocVertreter(List<Long> sensorCocIds) {

src/main/java/de/interfaceag/bmw/pzbk/berechtigung/MitarbeiterQnumberChangeController.java
package de.interfaceag.bmw.pzbk.berechtigung;

import de.interfaceag.bmw.pzbk.entities.Mitarbeiter;
import de.interfaceag.bmw.pzbk.localization.LocalizationService;
import org.primefaces.context.RequestContext;

import javax.faces.application.FacesMessage;
import javax.faces.application.FacesMessage.Severity;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;

/**
 * @author fn
 */
@Named
@ViewScoped
public class MitarbeiterQnumberChangeController implements Serializable {

    @Inject
    private QnumberChangeService qnumberChangeService;
    @Inject
    private LocalizationService localizationService;

    private Mitarbeiter mitarbeiterToEdit;

    private Mitarbeiter mitarbeiterFound;

    private String qnumberToSearch;

    public void showQnumberChangeDialog(Mitarbeiter mitarbeiterToEdit) {
        updateDialogData(mitarbeiterToEdit);
        RequestContext context = RequestContext.getCurrentInstance();
        context.update("dialog:changeQnumberDialogForm");
        context.execute("PF('changeQnumberDialog').show()");
    }

    private void updateDialogData(Mitarbeiter mitarbeiterToEdit) {
        this.mitarbeiterToEdit = mitarbeiterToEdit;
    }

    public void handleSuche() {
        mitarbeiterFound = qnumberChangeService.findMitarbeiterInLdapByQnumber(qnumberToSearch);
        if (mitarbeiterFound == null) {
            String message = localizationService.getValue("qnumberchangedialog_qnumber_not_found") + qnumberToSearch;
            writeMessageToGrowl(FacesMessage.SEVERITY_ERROR, message);
        }
    }

    public void processChanges() {
        if (qnumberToSearch == null || qnumberToSearch.isEmpty()) {
            String message = localizationService.getValue("qnumberchangedialog_qnumber_missing");
            writeMessageToGrowl(FacesMessage.SEVERITY_ERROR, message);
        } else {
            doQnumberChange();
        }
    }

    private void writeMessageToGrowl(Severity messageType, String message) {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        facesContext.addMessage(null, new FacesMessage(messageType, message, ""));
    }

    private void doQnumberChange() {
        boolean suceeded = qnumberChangeService.changeQnumber(mitarbeiterToEdit, qnumberToSearch);
        if (suceeded) {
            String message = localizationService.getValue("qnumberchangedialog_qnumber_changed");
            writeMessageToGrowl(FacesMessage.SEVERITY_INFO, message);
            RequestContext.getCurrentInstance().execute("PF('changeQnumberDialog').hide();");
        } else {
            String message = localizationService.getValue("qnumberchangedialog_qnumber_not_valid");
            writeMessageToGrowl(FacesMessage.SEVERITY_ERROR, message);
        }
    }

    public String getQnumberToSearch() {
        return qnumberToSearch;
    }

    public void setQnumberToSearch(String qNumberToSearch) {
        this.qnumberToSearch = qNumberToSearch;
    }

    public Mitarbeiter getMitarbeiterToEdit() {
        return mitarbeiterToEdit;
    }

    public Mitarbeiter getMitarbeiterFound() {
        return mitarbeiterFound;
    }

}

src/main/webapp/berechtigung/components/berechtigungContent.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets">
.
    <h:outputStylesheet library="css" name="main.css"/>
    <h:outputStylesheet library="css" name="button/text_button.css"/>
    <h:outputStylesheet library="css" name="button/button.css"/>
    <h:outputStylesheet library="css" name="berechtigungWorkflow/berechtigung.css"/>

    <h:body >
        <h:form id="mainContentForm">
            <div class="berechtigung-header">
                <h:outputLabel id="rolleLabel" value="#{msg.rolleFuerMitarbeiter}"/>
            </div>

            <div class="content-berechtigung-description">
                <h:outputLabel value="#{msg.berechtigungworkflow_rolle_desription}"/>
            </div>

            <div class="berechtigung-content">
                <p:selectOneMenu id="rollenOneMenu" value="#{berechtigungFlowController.viewData.selectedRole}">
                    <f:selectItems value="#{berechtigungFlowController.viewData.chooseableRoles}" var="rolle"/>
                </p:selectOneMenu>
            </div>

            <div class="footer">
                <p:commandButton id="proceedButton"
                                 value="#{msg.berechtigungworkflow_button_go_on}"
                                 process="@form"
                                 action="berechtigung-waehlen"
                                 styleClass="glass-button"
                                 actionListener="#{berechtigungFlowController.updateBerechtigungenForRole()}"/>
            </div>
        </h:form>
    </h:body>
</ui:composition>

src/main/webapp/berechtigung/components/berechtigungWaehlenContent.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets">

    <h:outputStylesheet library="css" name="main.css"/>
    <h:outputStylesheet library="css" name="accordion/accordion.css"/>
    <h:outputStylesheet library="css" name="button/text_button.css"/>
    <h:outputStylesheet library="css" name="button/button.css"/>
    <h:outputStylesheet library="css" name="berechtigungWorkflow/berechtigung.css"/>

    <h:body class="content">
        <h:form>
            <div class="berechtigung-header">
                <h:outputLabel id="selectedRolleLabel"
                               value="#{msg.berechtigungworkflow_choose} #{berechtigungFlowController.viewData.selectedRole}"/>
            </div>

            <div class="berechtigung-content-choose">

                <div class="berechtigung-accordion-panel-choose">
                    <p:accordionPanel rendered="#{berechtigungFlowController.viewData.berechtigungenForRoleWithLeserecht.berechtigungValue ne null}">
                        <p:tab title="#{msg.berechtigungworkflow_schreibrechte}">
                            <p:selectManyCheckbox
                                    collectionType="java.util.ArrayList"
                                    value="#{berechtigungFlowController.viewData.selectedBerechtigungenWithSchreibrecht}"
                                    converter="#{berechtigungFlowController.viewData.berechtigungWorkflowConverterForSchreibreccht}"
                                    rendered="#{berechtigungFlowController.viewData.berechtigungenForRoleWithSchreibrecht.berechtigungValue ne null
                                    and berechtigungFlowController.viewData.berechtigungenForRoleWithSchreibrecht.berechtigungValue.size() > 0}"
                                    layout="grid" columns="1">
                                <f:selectItems
                                        value="#{berechtigungFlowController.viewData.berechtigungenForRoleWithSchreibrecht.berechtigungValue}"
                                        var="berechtigung"
                                        itemValue="#{berechtigung}"
                                        itemLabel="#{berechtigung.value}"
                                        itemDisabled="#{berechtigungFlowController.viewData.isSchreibberechtigungSelectedInSLeseecht(berechtigung)}"/>
                                <p:ajax listener="#{berechtigungFlowController.viewData.selectedBerechtigungenWithSchreibrecht}" update="@form" />
                            </p:selectManyCheckbox>

                            <!-- empty state for schreib-rechte -->
                            <p:outputLabel
                                    rendered="#{berechtigungFlowController.viewData.berechtigungenForRoleWithSchreibrecht.berechtigungValue == null
                                    or berechtigungFlowController.viewData.berechtigungenForRoleWithSchreibrecht.berechtigungValue.size() == 0}"
                                    value="#{msg.berechtigungworkflow_empty_schreibrechte_to_choose}">
                            </p:outputLabel>
                        </p:tab>
                    </p:accordionPanel>
                </div>

                <div class="berechtigung-accordion-panel-choose padding-left" style="#{berechtigungFlowController.displayNoneWhenEcoc()}">
                    <p:accordionPanel>
                        <p:tab title="#{msg.berechtigungworkflow_leserechte}">
                            <p:selectManyCheckbox
                                    collectionType="java.util.ArrayList"
                                    value="#{berechtigungFlowController.viewData.selectedBerechtigungenWithLeserecht}"
                                    converter="#{berechtigungFlowController.viewData.berechtigungWorkflowConverterForLesereccht}"
                                    layout="grid" columns="1"
                                    rendered="#{berechtigungFlowController.viewData.berechtigungenForRoleWithLeserecht.berechtigungValue ne null
                                    and berechtigungFlowController.viewData.berechtigungenForRoleWithLeserecht.berechtigungValue.size() > 0}" >
                                <f:selectItems
                                        value="#{berechtigungFlowController.viewData.berechtigungenForRoleWithLeserecht.berechtigungValue}"
                                        var="berechtigung"
                                        itemValue="#{berechtigung}"
                                        itemLabel="#{berechtigung.value}"
                                        itemDisabled="#{berechtigungFlowController.viewData.isLeseberechtigungSelectedInSchreibrecht(berechtigung)}"/>
                                <p:ajax listener="#{berechtigungFlowController.viewData.selectedBerechtigungenWithLeserecht}" update="@form" />
                            </p:selectManyCheckbox>

                            <!-- empty state for lese-rechte -->
                            <p:outputLabel
                                    rendered="#{berechtigungFlowController.viewData.berechtigungenForRoleWithLeserecht.berechtigungValue == null
                                    or berechtigungFlowController.viewData.berechtigungenForRoleWithLeserecht.berechtigungValue.size() == 0}"
                                    value="#{msg.berechtigungworkflow_empty_leserechte_to_choose}">
                            </p:outputLabel>
                        </p:tab>
                    </p:accordionPanel>
                </div>
            </div>

            <div class="footer-berechtigung-waehlen">
                <p:commandButton value="#{msg.berechtigungworkflow_button_back}"
                                 styleClass="glass-button"
                                 actionListener="#{berechtigungFlowController.resetSelectedBerechtigungen()}"
                                 action="berechtigung"/>

                <p:commandButton value="#{msg.berechtigungworkflow_button_go_on}"
                                 styleClass="glass-button"
                                 action="summary"
                                 disabled="#{berechtigungFlowController.isButtonDisabled()}"
                                 process="@form"/>
            </div>
        </h:form>
    </h:body>
</ui:composition>

src/main/webapp/berechtigung/components/endpageContent.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:p="http://primefaces.org/ui" xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:outputStylesheet library="css" name="button/text_button.css"/>
    <h:outputStylesheet library="css" name="button/button.css"/>
    <h:outputStylesheet library="css" name="main.css"/>
    <h:outputStylesheet library="css" name="berechtigungWorkflow/berechtigung.css"/>

    <h:body class="content">
        <h:form>
            <div class="berechtigung-header">
                <h:outputLabel id="rolleLabel" value="#{msg.berechtigungworkflow_successfull}"/>
            </div>

            <div class="berechtigung-content">
                <h:outputText value="#{msg.berechtigungworkflow_endpage1}" />
            </div>

            <div class="berechtigung-content">
                <h:outputText value="#{msg.berechtigungworkflow_endpage2}" />
            </div>

            <div class="footer">

                <p:commandButton id="proceedButton"
                                 value="#{msg.berechtigungworkflow_zum_am_tool}"
                                 action="returnFromBerechtigungFlow"
                                 styleClass="glass-button ok-button"/>

            </div>
        </h:form>
    </h:body>
</ui:composition>