src/main/java/de/interfaceag/bmw/pzbk/entities/Anhang.java
package de.interfaceag.bmw.pzbk.entities;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Temporal;
import java.io.Serializable;
import java.util.Date;

import static javax.persistence.TemporalType.TIMESTAMP;

/**
 * @author Christian Schauer
 */
@Entity
@NamedQueries( {
        @NamedQuery(name = Anhang.GET_ANHANG_BY_ID, query = "SELECT anh FROM Anhang anh WHERE anh.id = :id"),
        @NamedQuery(name = Anhang.ANHANG_BY_NAME, query = "SELECT a FROM Anhang a WHERE a.dateiname LIKE :name"),
        @NamedQuery(name = Anhang.ANHANG_BY_CONTENT_ID, query = "SELECT a FROM Anhang a WHERE a.content.id = :id"),
        @NamedQuery(name = Anhang.GET_ANHANG_BY_ID_FETCH, query = "SELECT a FROM Anhang a "
                + "INNER JOIN FETCH a.content "
                + "WHERE a.id = :id")})
public class Anhang implements Serializable {

    // ------------  queries ---------------------------------------------------
    public static final String GET_ANHANG_BY_ID = "anhang.get_anhang_by_id";
    public static final String ANHANG_BY_NAME = "anhang_by_name";
    public static final String ANHANG_BY_CONTENT_ID = "anhang_by_content_id";
    public static final String GET_ANHANG_BY_ID_FETCH = "anhang.get_anhang_by_id_fetch";

    // ------------  fields ----------------------------------------------------
    @Id
    @SequenceGenerator(name = "anhang_id_seq",
            sequenceName = "anhang_id_seq",
            allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "anhang_id_seq")
    private Long id;

    private String dateiname;
    private String dateityp;
    private int filesize;
    private boolean standardBild;

    @Temporal(TIMESTAMP)
    private Date zeitstempel;
    @ManyToOne(fetch = FetchType.LAZY)
    private Mitarbeiter creator;
    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE}, fetch = FetchType.LAZY)
    private DbFile content;

    // ------------  constructors ----------------------------------------------
    public Anhang() {
        this.standardBild = false;
        this.content = new DbFile();
    }

    public Anhang(Mitarbeiter creator, String name, String type, DbFile content) {
        this.creator = creator;
        this.dateiname = name;
        this.dateityp = type;
        this.content = content;
        this.zeitstempel = new Date(System.currentTimeMillis());
        this.standardBild = false;
    }

    public Anhang(Mitarbeiter creator, String name, String type, byte[] content) {
        this.creator = creator;
        this.filesize = content.length;
        this.dateiname = name;
        this.dateityp = type;
        this.content = new DbFile(name, type, content);
        this.zeitstempel = new Date(System.currentTimeMillis());
        this.standardBild = false;
    }

    public Anhang(Mitarbeiter owner, DbFile content) {
        this.creator = owner;
        this.dateityp = content.getType();
        this.content = content;
        this.zeitstempel = new Date(System.currentTimeMillis());
        this.standardBild = false;
    }

    public Anhang(String name, DbFile content) {
        this.dateiname = name;
        this.dateityp = content.getType();
        this.content = content;
        this.filesize = content.getSize();
        this.zeitstempel = new Date(System.currentTimeMillis());
        this.standardBild = false;
    }

    // ------------  methods ---------------------------------------------------
    public static Anhang createTestAnhang(String supplement, Date date) {
        Anhang a = new Anhang();
        a.setDateiname("Dateiname_" + supplement);
        a.setZeitstempel(date);
        return a;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(" ").append("/").append(dateiname);
        sb.append("...").append(zeitstempel);
        return sb.toString();
    }

    @Override
    public int hashCode() {
        HashCodeBuilder hb = new HashCodeBuilder(23, 463);
        hb.append(id);
        hb.append(dateiname);
        hb.append(dateityp);
        hb.append(filesize);
        return hb.toHashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof Anhang)) {
            return false;
        }

        if (obj == this) {
            return true;
        }

        Anhang other = (Anhang) obj;
        EqualsBuilder eb = new EqualsBuilder();
        eb.append(id, other.id);
        eb.append(dateiname, other.dateiname);
        eb.append(dateityp, other.dateityp);
        eb.append(filesize, other.filesize);
        return eb.isEquals();
    }

    public String getFilesizeAsString() {
        float divisor = (float) 1024 * 1024;
        float sizeMb = this.filesize / divisor;
        String result;

        if (sizeMb < 0.01) {
            result = this.filesize + " Byte";
        } else if (sizeMb < 1.0) {
            result = this.filesize / 1024 + " kB";
        } else {
            result = String.format("%.2f", sizeMb) + " MB";
        }
        return result;
    }

    public Anhang getCopy() {
        Anhang anh = new Anhang();
        anh.setDateiname(dateiname);
        anh.setDateityp(dateityp);
        anh.setContent(content.getCopy());
        anh.setFilesize(filesize);
        anh.setZeitstempel(zeitstempel);
        anh.setStandardBild(isStandardBild());
        return anh;
    }

    // ------------  getter / setter -------------------------------------------
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDateiname() {
        return dateiname;
    }

    public void setDateiname(String dateiname) {
        this.dateiname = dateiname;
    }

    public Date getZeitstempel() {
        return new Date(zeitstempel.getTime());
    }

    public void setZeitstempel(Date zeitstempel) {
        this.zeitstempel = new Date(zeitstempel.getTime());
    }

    public DbFile getContent() {
        return content;
    }

    public void setContent(DbFile content) {
        this.content = content;
    }

    public Mitarbeiter getCreator() {
        return creator;
    }

    public void setCreator(Mitarbeiter creator) {
        this.creator = creator;
    }

    public String getDateityp() {
        return dateityp;
    }

    public void setDateityp(String dateityp) {
        this.dateityp = dateityp;
    }

    public int getFilesize() {
        return filesize;
    }

    public void setFilesize(int filesize) {
        this.filesize = filesize;
    }

    /**
     * @return the standardBild
     */
    public boolean isStandardBild() {
        return standardBild;
    }

    /**
     * @param standardBild the standardBild to set
     */
    public void setStandardBild(boolean standardBild) {
        this.standardBild = standardBild;
    }

} // end of class

src/main/java/de/interfaceag/bmw/pzbk/entities/Umsetzer.java
package de.interfaceag.bmw.pzbk.entities;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * @author Christian Schauer
 */
@Entity
@Table(name = "umsetzer")
@Cacheable(false)
@NamedQueries( {
        @NamedQuery(name = Umsetzer.BY_ID, query = "SELECT u FROM Umsetzer u WHERE u.id = :id")})
public class Umsetzer implements Serializable {

    // ------------  queries ---------------------------------------------------
    public static final String BY_ID = "umsetzer.by_id";

    // ------------  fields ----------------------------------------------------
    @Id
    @SequenceGenerator(name = "umsetzer_id_seq",
            sequenceName = "umsetzer_id_seq",
            allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "umsetzer_id_seq")
    @Column(name = "umsetzer_id")
    private Long id;

    @OneToOne(fetch = FetchType.LAZY)
    private ModulSeTeam seTeam;

    @OneToOne(fetch = FetchType.LAZY)
    private ModulKomponente komponente;

    // ------------  constructors ----------------------------------------------
    public Umsetzer() {
    }

    public Umsetzer(ModulSeTeam seTeam, ModulKomponente komponente) {
        this.seTeam = seTeam;
        this.komponente = komponente;
    }

    public Umsetzer(ModulSeTeam seTeam) {
        this.seTeam = seTeam;
        this.komponente = null;
    }

    // ------------  methods ---------------------------------------------------
    public Modul getModul() {
        if (this.seTeam != null) {
            return this.seTeam.getElternModul();
        } else {
            return null;
        }
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();

        if (seTeam != null) {
            if (seTeam.getElternModul() != null) {
                sb.append(seTeam.getElternModul().getName());
                sb.append(" > ");
            }

            sb.append(seTeam.getName());

            if (komponente != null) {
                sb.append(" > ");
                sb.append(komponente.getName());
            }
        }

        return sb.toString();
    }

    @Override
    public int hashCode() {
        HashCodeBuilder hb = new HashCodeBuilder(31, 89);
        hb.append(id);
        hb.append(seTeam);
        hb.append(komponente);
        return hb.toHashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof Umsetzer)) {
            return false;
        }
        if (obj == this) {
            return true;
        }
        Umsetzer executer = (Umsetzer) obj;
        EqualsBuilder eb = new EqualsBuilder();
        eb.append(id, executer.id);
        eb.append(seTeam, executer.seTeam);
        eb.append(komponente, executer.komponente);
        return eb.isEquals();
    }

    public Umsetzer getCopy() {
        Umsetzer u = new Umsetzer();
        u.setKomponente(komponente);
        u.setSeTeam(seTeam);
        return u;
    }

    // ------------  getter / setter -------------------------------------------
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public ModulSeTeam getSeTeam() {
        return seTeam;
    }

    public void setSeTeam(ModulSeTeam seTeam) {
        this.seTeam = seTeam;
    }

    public ModulKomponente getKomponente() {
        return komponente;
    }

    public void setKomponente(ModulKomponente komponente) {
        this.komponente = komponente;
    }

} // end of class

src/main/webapp/resources/anforderungOhneMeldungComps/anforderungOhneMeldungEditAnhangEditComp.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <!-- INTERFACE -->
    <cc:interface>
        <cc:attribute required="true" name="anforderungOhneMeldungEditController" type="de.interfaceag.bmw.pzbk.anforderungohnemeldungedit.AnforderungOhneMeldungEditController"/>
        <cc:attribute required="true" name="viewData" type="de.interfaceag.bmw.pzbk.anforderungohnemeldungedit.AnforderungOhneMeldungEditViewData"/>


    </cc:interface>

    <!-- IMPLEMENTATION -->
    <cc:implementation>
        <p:panel id="attachmentPanel" class="attachmentPanel">
            <p:fileUpload  id = "fileUploadCommandLink" update="attachmentPanel"
                           label="#{cc.attrs.viewData.anhaenge.size() > 0 ? '+' : msg.hinzufuegenDnD}"
                           mode="advanced"
                           dragDropSupport="true"
                           fileUploadListener="#{cc.attrs.anforderungOhneMeldungEditController.uploadAnhang}"
                           auto="true"
                           styleClass="#{cc.attrs.viewData.anhaenge.size() > 0 ? '' : 'empty'}" >


                <p:commandButton id="removeVorschaubildButton" value="#{msg.vorschaubildEntfernen}"
                                 rendered="#{cc.attrs.viewData.anhangForBild ne null}"
                                 actionListener="#{cc.attrs.viewData.removeVorschaubild()}"
                                 update="editAfo:anfoForm:anfoAccordion:anhangUpload:anhangTable"
                                 style="margin-left: 60px;" />


                <p:dataTable value="#{cc.attrs.viewData.anhaenge}"
                             class="fileUploadTable"
                             var="anhang"
                             rowKey="#{anhang.dateiname}"
                             id="anhangTable"
                             selection="#{cc.attrs.viewData.anhangForBild}"
                             rowIndexVar="index"
                             emptyMessage="#{msg.keinAnhangVorhanden}"
                             rendered="#{cc.attrs.viewData.anhaenge.size() > 0}">

                    <p:column class="fileUploadTableColumn" headerText="#{msg.dateien}">
                        <p:commandLink
                            actionListener="#{cc.attrs.anforderungOhneMeldungEditController.showAnhangGrafikDialog(anhang)}"
                            class="fileDownloadButton" immediate="true" update="@form"
                            rendered="#{anhang.dateityp == 'image/jpeg' or anhang.dateityp == 'image/png' or anhang.dateityp == 'jpg'}"
                            value="#{anhang.dateiname}">
                        </p:commandLink>
                        <p:commandButton ajax="false" id="anfoAnhangDl" class="fileDownloadButton" value="#{anhang.dateiname}" immediate="true"
                                         rendered="#{anhang.dateityp != 'image/jpeg' and anhang.dateityp != 'image/png' and anhang.dateityp != 'jpg'}">
                            <p:fileDownload value="#{cc.attrs.anforderungOhneMeldungEditController.downloadAnhang(anhang)}" />
                        </p:commandButton>
                    </p:column>

                    <p:column headerText="#{msg.dateigroesse}" width="100">
                        <h:outputText value="#{anhang.filesizeAsString}" />
                    </p:column>

                    <p:column selectionMode="single"
                              headerText="#{msg.alsTitelbild}"
                              style="text-align:center;visibility: #{anhang.dateityp == 'image/jpeg' or anhang.dateityp == 'image/png' or anhang.dateityp == 'jpg' or anhang == null ? 'visible' : 'hidden'}">
                    </p:column>

                    <p:column headerText="" width="100">
                        <p:commandLink class="anhangDelete" title="#{msg.entfernen}" id="fileuploadDeleteFile"
                                       actionListener = "#{cc.attrs.viewData.removeAnhang(anhang)}"
                                       update=":#{cc.clientId}:attachmentPanel" process=":#{cc.clientId}:attachmentPanel">
                            <p:collector value="#{anhang}" removeFrom="#{cc.attrs.viewData.anhaenge}" unique="true"/>
                            <img src="${facesContext.externalContext.requestContextPath}/resources/images/icons/color/icon_trash.png"/>
                        </p:commandLink>
                        <p:tooltip showDelay="500"  for="fileuploadDeleteFile"  position="top" value="#{msg.tooltipp_anfoMgmtObjectAnhangEditComp_Fileupload_deleteFile}" />
                    </p:column>
                </p:dataTable>
            </p:fileUpload>
        </p:panel>
    </cc:implementation>
</html>

src/main/webapp/resources/anforderungOhneMeldungComps/anforderungOhneMeldungEdit_navbarComp.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <!-- INTERFACE -->
    <cc:interface>
        <cc:attribute required="true" name="anforderungOhneMeldungEditController" type="de.interfaceag.bmw.pzbk.anforderungohnemeldungedit.AnforderungOhneMeldungEditController"/>
    </cc:interface>

    <!-- IMPLEMENTATION -->
    <cc:implementation>
        <div class="left" >
            <p:link id="prozessbaukastenZuordnenLink"
                    class="prozessbaukastenZuordnenLink"
                    outcome="prozessbaukastenView"
                    rendered="#{cc.attrs.anforderungOhneMeldungEditController.prozessbaukastenPresent}"
                    value="#{cc.attrs.anforderungOhneMeldungEditController.prozessbaukastenLinkName}"
                    >
                <f:param name="fachId" value="#{cc.attrs.anforderungOhneMeldungEditController.fachId}" />
                <f:param name="version" value="#{cc.attrs.anforderungOhneMeldungEditController.version}" />
            </p:link>
        </div>
        <div class="right editButtonWrapper">
            <p:commandLink class="d-iflex" id="AnfoEditSpeichernBtn"
                           onclick="save();" >
                <img src="${facesContext.externalContext.requestContextPath}/resources/images/icons/white/icon_save.png" class="glass"/>
            </p:commandLink>



            <p:tooltip showDelay="500"  for="AnfoEditSpeichernBtn" value="#{msg.speichern}"
                       showEvent="mouseover" hideEvent="mouseout" styleClass="anfoKommentTooltip"
                       trackMouse="true" position="none"/>
            <p:commandLink id="cancelAnfoButton" class="d-iflex"
                           action="#{cc.attrs.anforderungOhneMeldungEditController.cancel()}">
                <img src="${facesContext.externalContext.requestContextPath}/resources/images/icons/white/icon_cancel.png" class="glass"/>
            </p:commandLink>
            <p:tooltip showDelay="500"  for="cancelAnfoButton" value="#{msg.verwerfen}"
                       showEvent="mouseover" hideEvent="mouseout" styleClass="anfoKommentTooltip"
                       trackMouse="true" position="none"/>
        </div>
    </cc:implementation>
</html>

src/main/webapp/resources/anforderungOhneMeldungComps/anforderungOhneMeldungViewDialogs.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:dialogs="http://xmlns.jcp.org/jsf/composite/dialogs">

    <!-- INTERFACE -->
    <cc:interface>
        <cc:attribute required="false" name="modulFreigabeCommentDialog" type="de.interfaceag.bmw.pzbk.controller.dialogs.ModulFreigabeCommentDialog"/>
        <cc:attribute required="false" name="modulFreigabeProceedDialog" type="de.interfaceag.bmw.pzbk.controller.dialogs.ModulFreigabeProccedDialog"/>
        <cc:attribute required="false" name="anforderungPlausiKomChangedCtrl" type="de.interfaceag.bmw.pzbk.controller.dialogs.AnforderungChangedInStatusPlausiConfirmDialog" />
        <cc:attribute required="false" name="versionPlusCreateNewVersionDialog" type="de.interfaceag.bmw.pzbk.controller.dialogs.VersionPlusCreateNewVersionDialog" />
        <cc:attribute required="false" name="versionPlusKommentarDialog" type="de.interfaceag.bmw.pzbk.controller.dialogs.VersionPlusKommentarDialog" />
        <cc:attribute required="false" name="changeVersionProceedDialog" type="de.interfaceag.bmw.pzbk.controller.dialogs.ChangeVersionProceedDialog" />
        <cc:attribute required="false" name="statusChangeMethodChangeDialog" type="de.interfaceag.bmw.pzbk.controller.dialogs.StatusChangeMethodChangeDialog" />
        <cc:attribute required="false" name="statusChangeNextStatusDialog" type="de.interfaceag.bmw.pzbk.controller.dialogs.StatusChangeNextStatusDialog" />
        <cc:attribute required="false" name="derivatZuordnenDialogPersistDerivat" type="de.interfaceag.bmw.pzbk.controller.dialogs.DerivatZuordnenDialogPersistDerivat" />
        <cc:attribute required="false" name="derivatZuordnenDialog" type="de.interfaceag.bmw.pzbk.controller.dialogs.DerivatZuordnenDialog" />
        <cc:attribute required="false" name="derivatAnzeigenDialogDerivatForAnforderungList" type="de.interfaceag.bmw.pzbk.controller.dialogs.DerivatAnzeigenDialogDerivatForAnforderungList" />
        <cc:attribute required="false" name="derivatAnzeigenProceedDialog" type="de.interfaceag.bmw.pzbk.controller.dialogs.DerivatAnzeigenProceedDialog" />
        <cc:attribute required="false" name="prozessbaukastenZuordnenDialogFields" type="de.interfaceag.bmw.pzbk.prozessbaukasten.zuordnen.ProzessbaukastenZuordnenDialogFields" />
        <cc:attribute required="false" name="prozessbaukastenZuordnenDialogPersist" type="de.interfaceag.bmw.pzbk.prozessbaukasten.zuordnen.ProzessbaukastenZuordnenDialogMethods" />
    </cc:interface>

    <!-- IMPLEMENTATION -->
    <cc:implementation>
        <!-- Anforderung -->

        <h:form id="afoPlausKomChangedForm">
            <p:dialog id="anfoderungPlausiKomChangedDialog" class="customDialog"
                      dynamic="true"
                      header="#{msg.changedwarnung}"
                      widgetVar="anforderungOhneMeldungPlausiChangedDialog"
                      modal="true"
                      closable="true"
                      resizable="true"
                      width="500">
                <dialogs:anforderungPlausiChangedDialog id="anfoderungPlausiKomChangedDialogContent" 
                                                        anfoContr="#{cc.attrs.anforderungPlausiKomChangedCtrl}" />
            </p:dialog>
        </h:form>
        <h:form id="modulFreigabeForm" >
            <p:dialog id="modulFreigabeCommentDialog" class="customDialog"
                      dynamic="true"
                      header="#{msg.modul} #{msg.status} #{msg.kommentar}"
                      widgetVar="modulFreigabeCommentDialog"
                      modal="true"
                      closable="false"
                      resizable="true"
                      width="500">
                <dialogs:modulFreigabeCommentDialog id="modulFreigabeCommentDialogContent" anfoCtrl="#{cc.attrs.modulFreigabeCommentDialog}" proceed="#{cc.attrs.modulFreigabeProceedDialog}"/>
            </p:dialog>                
        </h:form>
        <h:form id="changeVersionDialogForm">
            <p:dialog id="changeVersionDialog" class="customDialog"
                      dynamic="true"
                      header="#{msg.vorherigeVersionAufKeineWeiterverfolgung}"
                      widgetVar="changeVersionDialog"
                      modal="true"
                      closable="true"
                      resizable="true"
                      width="500">
                <dialogs:changeVersionDialog id="changeVersionDialogContent" 
                                             changeVersionProceedDialog="#{cc.attrs.changeVersionProceedDialog}" />
            </p:dialog>
        </h:form>


        <h:form id="versionPlusForm">
            <p:dialog id="versionPlusDialog" class="customDialog"
                      dynamic="true"
                      header="#{msg.versionplus}"
                      widgetVar="versionPlusDialog"
                      modal="true"
                      resizable="true"
                      width="600">
                <dialogs:versionPlusDialog id="versionPlusDlgContent" versionPlusCreateNewVersionDialog="#{cc.attrs.versionPlusCreateNewVersionDialog}"
                                           versionPlusKommentarDialog="#{cc.attrs.versionPlusKommentarDialog}" />
            </p:dialog>
        </h:form>
        <h:form id="statusChangeForm">
            <p:dialog id="statusChangeDialog" class="customDialog"
                      dynamic="true"
                      header="#{msg.statusWechsel}"
                      widgetVar="statusChangeDialog"
                      modal="true"
                      resizable="true"
                      width="600">
                <dialogs:statusChangeDialog id="statusChangeDlgContent" statusChangeMethodChangeDialog="#{cc.attrs.statusChangeMethodChangeDialog}" statusChangeNextStatusDialog="#{cc.attrs.statusChangeNextStatusDialog}" />
            </p:dialog>
        </h:form>
        <h:form id="anfoModulCommentForm">
            <p:dialog id="anfoModulCommentDialog" class="customDialog"
                      dynamic="true"
                      header="#{msg.modul} #{msg.status} #{msg.kommentar}"
                      widgetVar="anfoModulCommentDialog"
                      modal="true"
                      closable="true"
                      resizable="false"
                      width="500">
                <dialogs:anfoModulCommentDialog id="anfoModulCommentDialogContent" modulFreigabeCommentDialog="#{cc.attrs.modulFreigabeCommentDialog}"/>
            </p:dialog>
        </h:form>
        <h:form id="derivateZuordnenForm">
            <p:dialog id="derivateZuordnenDialog" class="customDialog"    
                      dynamic="true"
                      closable="false"
                      header="#{msg.derivateZuordnen}"
                      widgetVar="derivateZuordnenDialog"
                      modal="true"
                      resizable="true"
                      width="500">
                <dialogs:newDerivateZuordnenDialog id="derivateZuordnenDlgContent" derivatZuordnenDialogPersistDerivat="#{cc.attrs.derivatZuordnenDialogPersistDerivat}" derivatZuordnenDialog="#{cc.attrs.derivatZuordnenDialog}" />
            </p:dialog>
        </h:form>   
        <h:form id="derivatenAnzeigenForm">
            <p:dialog id="derivatenAnzeigenDialog" class="customDialog"
                      dynamic="true"
                      closable="false"
                      header="#{msg.anforderungenNachZakUebertragen}"
                      widgetVar="derivatenAnzeigenDialog"
                      modal="true"
                      resizable="true"
                      width="600">
                <dialogs:newDerivatenAnzeigenDialog id="derivatenAnzeigenDlgContent" derivateListForAnforderung="#{cc.attrs.derivatAnzeigenDialogDerivatForAnforderungList}" derivatenAnzeigenProceedDialog="#{cc.attrs.derivatAnzeigenProceedDialog}" />                     
            </p:dialog>
        </h:form>      
        <h:form id="prozessbaukastenZuordnenForm">
            <p:dialog id="prozessbaukastenZuordnenDialog" class="customDialog"
                      dynamic="true"
                      closable="false"
                      header="#{msg.prozessbaukastenzuordnendialog_titel}"
                      widgetVar="prozessbaukastenZuordnenDialog"
                      modal="true"
                      resizable="true"
                      width="80%">
                <dialogs:prozessbaukastenZuordnenDialog id="prozessbaukastenZuordnenDialogContent" prozessbaukastenZuordnenDialogFields="#{cc.attrs.prozessbaukastenZuordnenDialogFields}" prozessbaukastenZuordnenDialogPersist="#{cc.attrs.prozessbaukastenZuordnenDialogPersist}" />                     
            </p:dialog>
        </h:form>

    </cc:implementation>
</html>